### ISSUE TITLE
connection все равно закрывается после каждого запроса

### ISSUE THREAD

**Issue by SamuilYu** [VityasZV/JointPython#13]
В бесконечном цикле создаются только нити, при этом в самих нитях тоже должны быть бесконечные циклы, на каждом витке которых принимается запрос и отправляется ответ.

**Comment by VityasZV** [comment]
по поводу бесконечных циклов в нитях - мне кажется они не нужны, ибо в таком случае мы жёстко ограничиваем себя в количестве одновременно обрабатываемых клиентов. Сейчас новый тред появляется когда нужно обработать новый запрос. 
Но возможно я не прав. Если следующий запрос от клиента прилетает уже не по server_socket, а по установленному с клиентом соединению - то скорее всего нужно делать  ровно так как ты предложил
