### ISSUE TITLE
обмен сообщениями не синхронизирован

### ISSUE THREAD

**Issue by VityasZV** [VityasZV/JointPython#22]
проблема скорее всего на стороне только клиента
Вот пример обмена сообщениями двух клиентов:
<img width="212" alt="Снимок экрана 2020-04-26 в 15 05 42" src="https://user-images.githubusercontent.com/41433372/80307122-d9c88a80-87cf-11ea-9576-39a2a70da3e8.png">
<img width="248" alt="Снимок экрана 2020-04-26 в 15 06 14" src="https://user-images.githubusercontent.com/41433372/80307125-dc2ae480-87cf-11ea-8c3e-19bb5caa5414.png">
<img width="236" alt="Снимок экрана 2020-04-26 в 15 06 26" src="https://user-images.githubusercontent.com/41433372/80307126-de8d3e80-87cf-11ea-8612-ceb3877de2cd.png">
Как видно, fuck не дошел до первого пользователя.

**Comment by SamuilYu** [comment]
Я повнимателнее изучу этот вопрос, но первое предположение: проблема не в синхронизации, а в том, как работает стандартный инпут\оутпут, потому что здесь чтение и запись в один и тот же поток, и думается, что если потоки разделить, то проблема пропадет. Опять же еще изучу.
